"""rename address

Revision ID: 675c70a9e618
Revises: bc3dd5e8d624
Create Date: 2024-10-04 00:07:52.208668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675c70a9e618'
down_revision = 'bc3dd5e8d624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
