"""rename department

Revision ID: bc3dd5e8d624
Revises: fc269e455921
Create Date: 2024-10-03 22:00:30.038409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3dd5e8d624'
down_revision = 'fc269e455921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department',
    'departments')
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
